//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mis_manager
    {
        public int id { get; set; }
        public string name { get; set; }
        public string addres { get; set; }
        public string phone { get; set; }
        public string subject { get; set; }
        public string @class { get; set; }
        public Nullable<System.DateTime> logDate { get; set; }
        public string remarks { get; set; }
    }
}
